version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/init.d:/docker-entrypoint-initdb.d:ro
      - ./db/seed:/seed:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped
    networks:
      - internal

  api:
    build: 
      context: ./server
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 8080
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SERPAPI_API_KEY: ${SERPAPI_API_KEY}
      RAG_TOP_K: 6
      AUTO_INGEST: "1"
      KNOWLEDGE_DIR: "/knowledge"
      VIRTUAL_HOST: api.${DOMAIN}
      LETSENCRYPT_HOST: api.${DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8080"
    volumes:
      - ./server/workflows:/app/workflows:ro
      - ./db/seed:/seed:ro
      - type: bind
        source: ./knowledge
        target: /knowledge
        bind:
          create_host_path: true
    restart: unless-stopped
    networks:
      - nginx-proxy
      - internal

  web:
    build: 
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: http://api.${DOMAIN}
    environment:
      VITE_API_BASE: http://api.${DOMAIN}
      VIRTUAL_HOST: ${DOMAIN},www.${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN},www.${DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    expose:
      - "5173"
    restart: unless-stopped
    networks:
      - nginx-proxy
      - internal

# Remove the nginx service - nginx-proxy will handle this

volumes:
  dbdata:
  letsencrypt:
  webroot:

networks:
  internal:
    internal: false
  nginx-proxy:
    external: true