version: "3.9"
services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/init.d:/docker-entrypoint-initdb.d

  api:
    build: ./server
    environment:
      NODE_ENV: production
      PORT: 8080
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      RAG_TOP_K: 6
      AUTO_INGEST: "1"
      KNOWLEDGE_DIR: "/knowledge"
    depends_on: [db]
    ports: ["8080:8080"]
    volumes:
      - ./server/workflows:/server/workflows:ro
      - ./db/seed:/seed:ro
      - type: bind
        source: ./knowledge
        target: /knowledge
        bind:
          create_host_path: true

  web:
    build: ./client
    environment:
      VITE_API_BASE: http://localhost:8080
    depends_on: [api]
    ports: ["5173:5173"]

volumes:
  dbdata: